version: '3.8'

services:

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}      
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  
    ports:
      - "5432:5432" 
    networks:
      - app-network


  backend:
    build: ./backend  
    container_name: node-backend
    depends_on:
      - db            
    environment:
      - DB_USER=${DB_USER}     
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - "3001:3000"   
    volumes:
      - ./backend:/app
    networks:
      - app-network
    command: ["node", "index.js"]

networks:
  app-network:
    driver: bridge
